version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: poetry run uvicorn app.api:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - neo4j

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: poetry run streamlit run app/ui.py --server.port 8501

  neo4j:
    image: neo4j:5.13
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
