FROM python:3.11-slim

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir poetry && poetry config virtualenvs.create false
RUN poetry install --only main

EXPOSE 8000
CMD ["poetry", "run", "uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8000"]
